name: Go

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: echo "Job status is ${{ job.status }}."

    - name: Set up Node
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: echo "Job status is ${{ job.status }}."
        
    - name: Install firestore emulator
    - run: npm install -g firebase-tools
    - run: npm ci
    - run: echo "Job status is ${{ job.status }}."
    
    - name: Run tests
    - run: sh test.sh
    - run: echo "Job status is ${{ job.status }}."
